# Generated by Django 4.1.7 on 2023-04-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_products_product_internal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_category_id', models.TextField(unique=True)),
                ('com_category_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.TextField(unique=True)),
                ('com_name', models.TextField()),
                ('com_address', models.TextField()),
                ('com_phone', models.TextField()),
                ('com_email', models.TextField()),
                ('com_description', models.TextField()),
                ('com_TAX_REG', models.TextField()),
                ('com_notes', models.TextField()),
                ('FK_com_category_id', models.ForeignKey(on_delete=set, to='base.com_category')),
            ],
        ),
    ]
