# Generated by Django 4.1.7 on 2023-04-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_com_tax_reg_companies_com_business_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='FK_com_category_id',
            new_name='FK_com_category',
        ),
    ]
