# Generated by Django 4.1.7 on 2023-04-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_payments_fk_com_id'),
        ('base', '0012_warehouses_warehouse_desc'),
    ]

    operations = [
    ]
