# Generated by Django 3.2.12 on 2023-04-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_internal_id',
            field=models.TextField(unique=True),
        ),
    ]
