# Generated by Django 4.2 on 2023-04-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_products_product_internal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='fk_specs_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.specs'),
        ),
    ]
