# Generated by Django 4.1.7 on 2023-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_com_category_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='com_TAX_REG',
            new_name='com_business_type',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='com_description',
            new_name='com_desc',
        ),
        migrations.AddField(
            model_name='companies',
            name='com_tax_reg',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
