# Generated by Django 4.1.7 on 2023-04-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_fk_com_category_companies_fk_com_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='FK_com_category_id',
        ),
    ]
