# Generated by Django 4.1.7 on 2023-04-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_companies_fk_com_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='FK_com_category_id',
            field=models.ForeignKey(default='', on_delete=set, to='base.com_category'),
            preserve_default=False,
        ),
    ]
