# Generated by Django 4.2 on 2023-04-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sizes_products_fk_size_id'),
        ('base', '0008_companies_fk_com_category_id'),
    ]

    operations = [
    ]
