# Generated by Django 4.1.7 on 2023-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_merge_20230416_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.TextField()),
                ('payment_username', models.TextField()),
                ('payment_paid', models.TextField()),
                ('payment_method', models.TextField()),
                ('payment_comments', models.TextField()),
                ('payment_date', models.DateField()),
                ('payment_tot_require', models.DecimalField(decimal_places=2, max_digits=25)),
                ('payment_tot_remind', models.DecimalField(decimal_places=2, max_digits=25)),
                ('FK_com_id', models.ForeignKey(on_delete=set, to='base.com_category')),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.TextField()),
                ('contact_phone', models.TextField()),
                ('contact_position', models.TextField()),
                ('contact_notes', models.TextField()),
                ('contact_email', models.TextField()),
                ('FK_com_category_id', models.ForeignKey(on_delete=set, to='base.com_category')),
                ('FK_com_id', models.ForeignKey(on_delete=set, to='base.companies')),
            ],
        ),
    ]
