# Generated by Django 4.2 on 2023-04-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_merge_20230416_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.TextField(unique=True)),
            ],
        ),
    ]
