# Generated by Django 4.2 on 2023-04-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_warehouses'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('fk_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.products')),
                ('fk_warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.warehouses')),
            ],
        ),
    ]
