# Generated by Django 4.1.7 on 2023-04-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_payments_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='FK_com_id',
            field=models.ForeignKey(on_delete=set, to='base.companies'),
        ),
    ]
