# Generated by Django 4.2 on 2023-04-26 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_merge_20230425_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupRols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField()),
                ('group_desc', models.TextField()),
                ('FK_UserCreatedid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('user_password', models.TextField()),
                ('user_created_id', models.IntegerField(default='None')),
                ('FK_group_rol_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.grouprols')),
            ],
        ),
    ]
