---
  # Play1 - WebServer related tasks
  - name: Play Web - Create apache directories and username in web servers
    hosts: target
    become: true
    become_user: root
    tasks:
      
      - name: Create a username for tomcat
        user:
          name: ahmedmattar
          group: users
          shell: /bin/bash
          home: /home/ahmedmattar
