---
  # Play1 - WebServer related tasks
  - name: Play Web - Create apache directories and username in web servers
    hosts: target
    become: true
    become_user: root
    tasks:
      
      - name: Run the equivalent of "apt-get update" as a separate step
        apt:
          update_cache: yes
      - name: Install latest version of "Python3" 
        apt:
          name: 
          - python3
          - python3-pip
          state: latest
      
      - name: copy a file from remote machine to remote machine
        copy:
          src: ~/artifact.tar.gz
          dest: ~/artifact.tar.gz
