---
  # Play1 - WebServer related tasks
  - name: Play Web - Create apache directories and username in web servers
    hosts: target
    become: true
    become_user: root
    tasks:
      
      - name: Run the equivalent of "apt-get update" as a separate step
        apt:
          update_cache: yes
      - name: Install latest version of "Python3" 
        apt:
          name: 
          - python3
          - python3-pip
          state: latest
      
      - name: copy a file from testing machine to remote machine
        copy:
          src: ~/artifact.tar.gz
          dest: /home/ubuntu/artifact.tar.gz

      - name: Unarchive a file that is already on the remote machine
        unarchive:
          src: /home/ubuntu/artifact.tar.gz
          dest: /home/ubuntu/
          remote_src: yes
      
      - name: Install specified python requirements
        pip:
          requirements: /home/ubuntu/App/requirements.txt

      - name: Run the App
        shell: python3 manage.py runserver
        args:
          executable: /bin/python3